<a href="https://colab.research.google.com/github/Bhagirath369/Phi_Calculation_and_Simulation_in_ANNs/blob/main/MINST_CLASSIFICATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MINST CLASSIFICATION
## Extracting the 4 hidden neurons

In [ ]:
from tensorflow.keras import Input
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Flatten, Dense
from tensorflow import keras
from tensorflow.keras.utils import to_categorical

(X_train, Y_train),(X_test, Y_test) = keras.datasets.mnist.load_data()
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

y_train = to_categorical(Y_train, 10)
y_test = to_categorical(Y_test, 10)

# Define input explicitly
input_layer = Input(shape=(28, 28))
flattened = Flatten()(input_layer)
hidden = Dense(4, activation='relu')(flattened)
output = Dense(10, activation='softmax')(hidden)

# Build and compile model
model = Model(inputs=input_layer, outputs=output)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=3)

# Safely extracting any layer:
reduced_model = Model(inputs=model.input, outputs=hidden)


Epoch 1/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.5647 - loss: 1.3988
Epoch 2/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8046 - loss: 0.6523
Epoch 3/3
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8268 - loss: 0.5734


# Simulating all 16 Binary Inputs




In [ ]:
from tensorflow.keras.layers import Input
import numpy as np

# Create a manual 4-input model (to match binary inputs)
input_layer = Input(shape=(4,))
hidden = Dense(4, activation='relu')(input_layer)
reduced_model = Model(inputs=input_layer, outputs=hidden)

# Optionally train it on dummy binary data:
x_bin = np.array([[int(x) for x in format(i, '04b')] for i in range(16)])
y_bin = np.random.randint(0, 2, (16, 4))
reduced_model.compile(optimizer='adam', loss='mse')
reduced_model.fit(x_bin, y_bin, epochs=100, verbose=0)


# Run 16 Binary Inputs Through the Model

In [ ]:
# Reuse the 16 binary states
binary_inputs = np.array([[int(x) for x in format(i, '04b')] for i in range(16)])

# Run through reduced model
outputs = reduced_model.predict(binary_inputs, verbose=0)
print("Outputs: \n",outputs,"\n")

# Binarize outputs (e.g., activation > 0.5 = 1)
binarized_outputs = (outputs > 0.5).astype(int)

# TPM: current → next state
tpm = binarized_outputs
print("TPM shape:", tpm.shape)
print("TPM:\n", tpm)


Outputs: 
 [[0.         0.         0.08568706 0.        ]
 [0.5836316  0.         0.03117333 0.        ]
 [0.         0.         0.         0.20972581]
 [0.18490545 0.         0.         0.        ]
 [0.5883962  0.6568291  0.19462201 0.        ]
 [1.2620331  0.28334907 0.14010829 0.        ]
 [0.18967007 0.5340871  0.         0.        ]
 [0.863307   0.1606071  0.         0.        ]
 [0.5303606  0.4304913  0.3735573  0.        ]
 [1.2039975  0.05701125 0.31904358 0.        ]
 [0.13163446 0.30774933 0.         0.        ]
 [0.8052713  0.         0.         0.        ]
 [1.208762   1.1295154  0.48249224 0.        ]
 [1.882399   0.7560354  0.42797852 0.        ]
 [0.81003594 1.0067735  0.         0.        ]
 [1.4836729  0.63329345 0.         0.        ]] 

TPM shape: (16, 4)
TPM:
 [[0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 1 0 0]]


In [ ]:
connectivity_matrix = np.ones((4, 4), dtype=int) - np.eye(4, dtype=int)



In [ ]:
print("Connectivity Matrix:\n",connectivity_matrix)

Connectivity Matrix:
 [[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


In [ ]:
x_bin = np.array([[int(x) for x in format(i, '04b')] for i in range(16)])
y_bin = np.random.randint(0, 2, (16, 4))
print(x_bin,"\n")
print(y_bin)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]] 

[[1 1 1 1]
 [0 1 0 0]
 [1 0 0 1]
 [1 1 0 1]
 [0 1 1 0]
 [1 1 1 0]
 [0 1 0 1]
 [1 0 0 1]
 [0 1 1 1]
 [0 0 0 1]
 [1 0 0 1]
 [1 0 0 0]
 [0 0 0 0]
 [1 1 0 1]
 [0 1 0 1]
 [1 1 0 0]]


In [ ]:
!python -m pip install -U git+https://github.com/wmayner/pyphi.git@feature/iit-4.0

  Cloning https://github.com/wmayner/pyphi.git (to revision feature/iit-4.0) to /tmp/pip-req-build-foe6sizo
  Running command git clone --filter=blob:none --quiet https://github.com/wmayner/pyphi.git /tmp/pip-req-build-foe6sizo
  Resolved https://github.com/wmayner/pyphi.git to commit 941c65ad81286bc4c33fed9a6669e7566a5d4171
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 63.2 MB/s eta 0:00:00
  Created wheel for pyphi: filename=pyphi-2.0.0a1-py3-none-any.whl size=699477 sha256=373ba35b12bfeace094d31d6a2027fd9073c5d598f018f0034756cfceac7b00f
  Stored in directory: /tmp/pip-ephem-wheel-cache-moq2ui1r/wheels/3b/74/de/fcf0c56231d1dc4bc2ac9a33b180c5ed4d3b2ed7a9090a63b2
Successfully built pyphi


In [ ]:
import pyphi
import numpy as np
import itertools

pyphi.config.PROGRESS_BARS = False
pyphi.config.PARALLEL = False
#pyphi.config.SHORTCIRCUIT_SIA = False
#pyphi.config.VALIDATE_SUBSYSTEM_STATES = False


Welcome to PyPhi!

If you use PyPhi in your research, please cite the paper:

  Mayner WGP, Marshall W, Albantakis L, Findlay G, Marchman R, Tononi G.
  (2018). PyPhi: A toolbox for integrated information theory.
  PLOS Computational Biology 14(7): e1006343.
  https://doi.org/10.1371/journal.pcbi.1006343

Documentation is available online (or with the built-in `help()` function):
  https://pyphi.readthedocs.io

To report issues, please use the issue tracker on the GitHub repository:
  https://github.com/wmayner/pyphi

For general discussion, you are welcome to join the pyphi-users group:
  https://groups.google.com/forum/#!forum/pyphi-users

To suppress this message, either:
  - Set `WELCOME_OFF: true` in your `pyphi_config.yml` file, or
  - Set the environment variable PYPHI_WELCOME_OFF to any value in your shell:
        export PYPHI_WELCOME_OFF='yes'



In [ ]:
print('Substrate TPM: \n(input state) : probability that units turn ON')
input_state=binary_inputs
transition_probability=outputs
for input_state, transition_probability in zip(input_state, transition_probability):
  print(f'{input_state} : {transition_probability}')

Substrate TPM: 
(input state) : probability that units turn ON
[0 0 0 0] : [0.         0.         0.08568706 0.        ]
[0 0 0 1] : [0.5836316  0.         0.03117333 0.        ]
[0 0 1 0] : [0.         0.         0.         0.20972581]
[0 0 1 1] : [0.18490545 0.         0.         0.        ]
[0 1 0 0] : [0.5883962  0.6568291  0.19462201 0.        ]
[0 1 0 1] : [1.2620331  0.28334907 0.14010829 0.        ]
[0 1 1 0] : [0.18967007 0.5340871  0.         0.        ]
[0 1 1 1] : [0.863307  0.1606071 0.        0.       ]
[1 0 0 0] : [0.5303606 0.4304913 0.3735573 0.       ]
[1 0 0 1] : [1.2039975  0.05701125 0.31904358 0.        ]
[1 0 1 0] : [0.13163446 0.30774933 0.         0.        ]
[1 0 1 1] : [0.8052713 0.        0.        0.       ]
[1 1 0 0] : [1.208762   1.1295154  0.48249224 0.        ]
[1 1 0 1] : [1.882399   0.7560354  0.42797852 0.        ]
[1 1 1 0] : [0.81003594 1.0067735  0.         0.        ]
[1 1 1 1] : [1.4836729  0.63329345 0.         0.        ]


In [ ]:
print('Substrate TPM: \n(input state) : Binarized TPM(activation>0.5)')
input_state=binary_inputs
transition_probability=tpm
for input_state, transition_probability in zip(input_state, transition_probability):
  print(f'{input_state} : {transition_probability}')

Substrate TPM: 
(input state) : Binarized TPM(activation>0.5)
[0 0 0 0] : [0 0 0 0]
[0 0 0 1] : [1 0 0 0]
[0 0 1 0] : [0 0 0 0]
[0 0 1 1] : [0 0 0 0]
[0 1 0 0] : [1 1 0 0]
[0 1 0 1] : [1 0 0 0]
[0 1 1 0] : [0 1 0 0]
[0 1 1 1] : [1 0 0 0]
[1 0 0 0] : [1 0 0 0]
[1 0 0 1] : [1 0 0 0]
[1 0 1 0] : [0 0 0 0]
[1 0 1 1] : [1 0 0 0]
[1 1 0 0] : [1 1 0 0]
[1 1 0 1] : [1 1 0 0]
[1 1 1 0] : [1 1 0 0]
[1 1 1 1] : [1 1 0 0]


In [ ]:
!pip install 'pyphi[parallel]'


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.9/68.9 MB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 31.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 67.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.5/201.5 kB 15.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.5/118.5 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.2/196.2 kB 15.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 kB 29.8 MB/s eta 0:00:00


In [28]:
import pyphi
import numpy as np

# ✅ Disable parallel to avoid MissingOptionalDependenciesError
pyphi.config.PARALLEL = False

# Define TPM and connectivity matrix
tpm = np.array([
    [0,0,0,0],
    [0,0,0,0],
    [0,0,1,0],
    [0,1,1,0],
    [0,0,0,0],
    [0,1,0,0],
    [0,1,1,0],
    [0,1,1,0],
    [0,0,0,0],
    [0,0,0,0],
    [1,0,1,1],
    [0,1,1,0],
    [1,0,0,0],
    [0,0,0,0],
    [1,0,1,1],
    [0,1,1,0]
])

cm = np.array([
    [0,1,1,1],
    [1,0,1,1],
    [1,1,0,1],
    [1,1,1,0]
])

labels = ('N0', 'N1', 'N2', 'N3')
network = pyphi.Network(tpm, cm, node_labels=labels)

print("State     Φ (phi)")
print("------------------")
for i in range(16):
    state = tuple(int(x) for x in format(i, '04b'))
    subsystem = pyphi.Subsystem(network, state)
    phi = pyphi.compute.phi(subsystem)


State     Φ (phi)
------------------


MissingOptionalDependenciesError: Please re-install PyPhi with `pyphi[parallel]` to use this feature.